# Generated by Django 3.2.7 on 2021-09-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagensmodel',
            name='img',
            field=models.ImageField(blank=True, upload_to='all_images/'),
        ),
    ]
